#!/bin/bash
# Usage: ./opkg-create-package DIR
#   Where DIR is directory where package template is stored
#  Output package is placed to current directory and is in format NAME.ipk where
#  NAME is package name from control file

ORG=`pwd`

[ -n "$1" ] && cd $1

NAME=`grep -E "^Package:" control/control | sed 's/^Package:[ ]*//;s/[ ]*$//'`

# First lets generate files-md5sum file
find data -type f | xargs sha256sum > control/files-sha256
sed -i 's/ data/ /' control/files-sha256

# create control.tar.gz
cd control
tar -czf ../control.tar.gz .
rm files-sha256
cd ..

# package data
cd data
tar -czf ../data.tar.gz .
cd ..

# create package
echo 2 > debian-binary
tar -czf $ORG/$NAME.ipk ./debian-binary ./control.tar.gz ./data.tar.gz
rm debian-binary
rm control.tar.gz
rm data.tar.gz
