#!/bin/bash
# Usage: Just start this script in directory where you have all your packages
set -eu

rm -f Packages
touch Packages
for pkg in *.ipk; do
	control="$(tar -xOzf "$pkg" ./control.tar.gz | tar -xOzf - ./control)"

	{
		sed -n '/^Description:/q;p' <<<"$control"
		echo "Filename: $pkg"
		echo "MD5Sum: $(md5sum "$pkg" | cut -f1 -d' ')"
		sha256="$(sha256sum "$pkg" | cut -f1 -d' ')"
		echo "SHA256sum: $sha256"
		echo "SHA256Sum: $sha256"
		sed -n '/^Description:/,$p' <<<"$control"
		echo
	} >> Packages
	gzip -fk Packages
done
