#!/bin/sh /etc/rc.common

START=85

status() {
	return 0
}

start() {
	# Recover updater's journal if it exists
	if [ -e "/usr/share/updater/journal" ]; then
		# If journal recovery is successful then updater should be run again
		# because it might not be finished because of replan package option.
		opkg-trans -s dbg -j && updater.sh
	fi
}

stop() {
	:
}

restart() {
	:
}

reload() {
	:
}
