#!/bin/sh

set -ex
mkdir -p hashes.new
for version in 2 ; do
	for serie in 00000003 00000005 00000006 00000007 00000008 00000009 ; do
		./hash_files.pl -u https://api.turris.cz/updater-repo/$version/$serie -o hashes.new/$version.$serie.json -l core -d definitions -b generic -b master -b nightly -b nospy -b rc -b stable -b testing
	done
done
xz -9 hashes.new/*.json
