#!/bin/sh
set -e
DIR="$1"

ORIG="$(pwd)"
mkdir -p "$DIR"
cd "$DIR"
gzip -dc | tar x
mkdir control
cd control
gzip -dc <../control.tar.gz | tar x
(cat conffiles 2>/dev/null || true) | sed -e 's/^/-/'
cd ..
mkdir data
cd data
gzip -dc <../data.tar.gz | tar x
find -type l >../links
IFS='	'
if [ -s ../links ] ; then
	xargs -d'\n' readlink <../links | paste - ../links | grep '^/' | while read PATH LINK ; do
		/bin/rm "$LINK"
		/bin/ln -sf ."$PATH" "$LINK"
	done
fi
find -L -type f -not -path './etc/uci-defaults/*' -and -not -path './tmp/*' -and -not -path ./etc/unbound/root.key -and -not -path './etc/rainbow.magic' -and -not -path './etc/services' -and -not -path './etc/config/ucitrack' -and -not -path './usr/bin/killall' -and -not -path './etc/ssl/certs/33815e15.0' -print0 | xargs -0 md5sum -b | (grep -v -e '-$' || true)
cd "$ORIG"
rm -rf "$DIR"
