#!/bin/sh /etc/rc.common

# We want to run after updater (S85)
START=86

# Note: we can't use PROCD as with it we can't deny service stop.

start() {
	(
	exec 0>&-
	exec 1>&-
	exec 2>&-
	updater-migrate.sh --batch 2>&1 | logger -t "updater-migrate"
	) &
}

stop() {
	# As part of migration, package containing this init script is removed and so
	# disabled. This would result into service kill and migration breakage.
	true
}
