image: gl-ci-turris-testing

stages:
  - test
  - pages

before_script:
  - git submodule init
  - git submodule update

# Test stage - run application tests
test:
  stage: test
  script:
    - make test test-sys

#test_valgrind:
#  stage: test
#  script:
#    - make valgrind valgrind-sys

# Test stage with busybox embedded
test_busybox:
  stage: test
  script:
    - BUSYBOX_EXEC=/bin/busybox make check

#test_valgrind_busybox:
#  stage: test
#  script:
#    - BUSYBOX_EXEC=/bin/busybox make valgrind valgrind-sys

pages:
  stage: pages
  script:
  - rm -rf public
  - mkdir public
  - make COV=y
  - make COV=y test test-sys
  - make COV=y coverage
  - markdown .doc_index.md > public/index.html
  - utils/gendocindex.sh | markdown > public/docindex.html
  - cp -r docs public/docs
  - cp -r coverage public/coverage
  artifacts:
    when: on_success
    paths:
    - public
  only:
  - master
