variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - pages

## Build stage ###################################################################
.build:
  stage: build
  script:
    - ./bootstrap
    - ./configure --disable-tests --disable-docs
    - make
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
    - config.log

build-debian-stable:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:debian

build-debian-unstable:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:tests

build-alpine:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:alpine

## Test stage ####################################################################
.test:
  stage: test
  image: registry.labs.nic.cz/turris/updater/updater:tests
  before_script:
      - ./bootstrap
      - ./configure

.test-check:
  extends: .test
  artifacts:
    expire_in: 1 week
    paths:
    - test-suite*.log
    - tests/*/*.log
    - tests/*/*.trs

check:
  extends: .test-check
  script:
    - make check

valgrind-memcheck:
  extends: .test-check
  script:
    - make check-valgrind-memcheck

# TODO possibly run sgcheck?

lint-c:
  extends: .test
  script:
    - make lint-c

lint-lua:
  extends: .test
  script:
    - make lint-lua
