stages:
  - build
  - test
  - pages

before_script:
  - git submodule update --init --recursive

## Build stage ###################################################################
.build:
  stage: build
  script:
    - make

build-debian-stable:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:debian

build-debian-unstable:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:tests

build-debian-alpine:
  extends: .build
  image: registry.labs.nic.cz/turris/updater/updater:alpine

## Test stage ####################################################################
.test:
  stage: test
  image: registry.labs.nic.cz/turris/updater/updater:tests

# Unit tests #
unit-tests:
  extends: .test
  script:
    - make test

unit-valgrind-tests:
  extends: .test
  script:
    - make OPENSSL_PURITY=y valgrind

# System integration tests #
system-tests:
  extends: .test
  script:
    - make test-sys

system-valgrind-tests:
  extends: .test
  script:
    - make OPENSSL_PURITY=y valgrind-sys

# Static checkers #
cppcheck:
  extends: .test
  script:
    - make cppcheck

luacheck:
  extends: .test
  script:
    - make luacheck

## Pages stage ###################################################################
pages:
  stage: pages
  image: registry.labs.nic.cz/turris/updater/updater:tests
  script:
  - rm -rf public
  - mkdir public
  - make COV=y
  - make COV=y test test-sys
  - make COV=y coverage
  - markdown .doc_index.md > public/index.html
  - utils/gendocindex.sh | markdown > public/docindex.html
  - cp -r docs public/docs
  - cp -r coverage public/coverage
  artifacts:
    when: on_success
    paths:
    - public
  only:
  - master
