image: gl-ci-turris-testing

stages:
  - test

before_script:
  - git submodule init
  - git submodule update

# Test stage - run application tests
test:
  stage: test

  script:
    - make check

# Test stage with busybox embedded
test_busybox:
  stage: test

  script:
    - BUSYBOX_EXEC=/bin/busybox make check
