image: registry.labs.nic.cz/turris/updater

stages:
  - test
  - pages

before_script:
  - git submodule init
  - git submodule update

# Unit tests #
unit-tests:
  stage: test
  script:
    - make test

unit-valgrind-tests:
  stage: test
  script:
    - make OPENSSL_PURITY=y valgrind

# System integration tests #
system-tests:
  stage: test
  script:
    - make test-sys

system-valgrind-tests:
  stage: test
  script:
    - make OPENSSL_PURITY=y valgrind-sys

# Static checkers #
cppcheck:
  stage: test
  script:
    - make cppcheck

luacheck:
  stage: test
  script:
    - make luacheck

# Gitlab pages #
pages:
  stage: pages
  script:
  - rm -rf public
  - mkdir public
  - make COV=y
  - make COV=y test test-sys
  - make COV=y coverage
  - markdown .doc_index.md > public/index.html
  - utils/gendocindex.sh | markdown > public/docindex.html
  - cp -r docs public/docs
  - cp -r coverage public/coverage
  artifacts:
    when: on_success
    paths:
    - public
  only:
  - master
