VALGRIND:=valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes --trace-children=no --child-silent-after-fork=yes --error-exitcode=1
include $(S)/build/Makefile.top

include $(S)/design/Makefile.dir
include $(S)/src/Makefile.dir
include $(S)/tests/Makefile.dir

include $(S)/build/Makefile.dir
include $(S)/build/Makefile.bottom
