LUA_NAME := $(shell for lua in lua5.1 lua ; do if pkg-config $$lua ; then echo $$lua ; break ; fi ; done)
VALGRIND:=valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes --error-exitcode=1
include $(S)/build/Makefile.top

include $(S)/design/Makefile.dir
include $(S)/src/Makefile.dir
include $(S)/tests/Makefile.dir

include $(S)/build/Makefile.dir
include $(S)/build/Makefile.bottom
