# This file contains configuration of the build. It may be generated by some
# script in the future.

# The RELATIVE variable is for the wrapper makefiles.
O := $(RELATIVE).
S := $(RELATIVE).
ASCIIDOC := asciidoc

include $(S)/Makefile.dir

