#!/bin/sh
TIME=$(( $(tr -cd 0-9 </dev/urandom | head -c 8 | sed -e 's/^0*//' ) % 60 ))
if [ -z "$TIME" ] ; then
	TIME=0
fi
echo 'MAILTO=""' >"$IPKG_INSTROOT"/etc/cron.d/updater
echo "$TIME	*       *       *       *       root	/usr/bin/updater.sh >/dev/null 2>&1 &" >>"$IPKG_INSTROOT"/etc/cron.d/updater
echo "0	0	*	*	*	root	/usr/bin/updater-unstuck.sh >/dev/null 2>&1 &" >>"$IPKG_INSTROOT"/etc/cron.d/updater
[ -n "$IPKG_INSTROOT" ] || {
if [ -x /usr/sbin/cert-backup ] ; then
	/usr/sbin/cert-backup /usr/share/updater/keys/standby.pem /usr/share/updater/keys/release.pem /etc/ssl/updater.pem
fi
if uci get -q updater.pkglists.configured || uci get -q updater.pkglists.lists | grep -q . ; then
	:
else
	uci add_list updater.pkglists.lists=luci-controls
	uci add_list updater.pkglists.lists=nas
	uci add_list updater.pkglists.lists=printserver
	uci add_list updater.pkglists.lists=netutils
fi
uci set updater.pkglists.configured=1
uci commit updater
/etc/init.d/updater enable
true # The previous sometimes returns 1 without any reason. Ignore it.
# No need to start here, it is not a daemon, just a start-up check
}
