#!/bin/sh
# Updater it self is not aware of approvals. Those are completely handled in
# updater-supervisor. But when updater does something to system it's most probable
# that it invalidated current approval request. So this script just removes it
# every time update proceeds.
rm -f /usr/share/updater/approvals
