--[[
Do not edit this file. It is the entry point. Create new file in conf.d instead.

Also note that for migration purpose this file is compiled in to the updater
library and so changes in this file won't affect pkgupdate execution. This file
is here just for illustration.
]]

-- Prepare variables specifying localization of system.
l10n = {} -- table with selected localizations
Export('l10n')
-- This is helper function for including localization packages.
function for_l10n(fragment)
	for _, lang in pairs(l10n or {}) do
		Install(fragment .. lang, {ignore = {"missing"}})
	end
end
Export('for_l10n')

-- Load all lua scripts from /etc/updater/conf.d
local conf_dir = root_dir .. '/etc/updater/conf.d'
local confd_type, _ = stat(conf_dir)
if confd_type == 'd' then
	for name, tp in pairs(ls(conf_dir)) do
		if tp == 'r' and name:match('.*.lua') then
			Script("conf.d-" .. name:sub(1, name:find('.lua$') - 1), 'file://' .. conf_dir .. '/' .. name, { security = "Local" })
		end
	end
else
	DIE('No ' .. conf_dir .. ' directory!')
end
