# Container for compilation test against musl system
# We choose AlpineLinux because OpenWRT compiler is not as easy to setup

FROM alpine:3.11

ENV HOME /root

RUN \
  apk update upgrade && \
  apk add \
      ca-certificates curl git coreutils \
      make cmake pkgconf gcc perl perl-file-slurp \
      libtool automake autoconf autoconf-archive \
      musl-dev \
      curl-dev libevent-dev uriparser-dev \
      libarchive-dev \
      uthash-dev \
      lua5.1-dev \
      asciidoc bash

# argp-standalone with -fPIC
RUN \
  wget "http://www.lysator.liu.se/~nisse/misc/argp-standalone-1.3.tar.gz" && \
  tar -xzf "argp-standalone-1.3.tar.gz" && rm "argp-standalone-1.3.tar.gz" && \
  cd "argp-standalone-1.3" && \
  wget https://git.alpinelinux.org/aports/plain/main/argp-standalone/001-throw-in-funcdef.patch && \
  wget https://git.alpinelinux.org/aports/plain/main/argp-standalone/gnu89-inline.patch && \
  patch <001-throw-in-funcdef.patch && patch <gnu89-inline.patch && \
  CFLAGS=-fPIC ./configure && make && \
  cp argp.h /usr/include && cp libargp.a /usr/lib/ && \
  cd .. && rm -rf "argp-standalone-1.3"


CMD [ "bash" ]

# vim: ft=dockerfile
