# Container used to run all tests and to generate documentation and gitlab pages.

FROM debian:unstable

ENV HOME /root

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get -y install --no-install-recommends \
    busybox ca-certificates curl git bzip2 \
    autoconf autoconf-archive automake libtool \
    make cmake pkg-config gcc \
    check cppcheck lua-check valgrind \
    libcurl4-openssl-dev libevent-dev libssl-dev liburiparser-dev \
    libarchive-dev \
    uthash-dev \
    liblua5.1-0-dev \
    asciidoc lcov markdown libcommon-sense-perl \
    && \
  apt-get clean

# Compile base64c
RUN \
  git clone --branch "v0.2.1" "https://gitlab.nic.cz/turris/base64c.git" && \
  cd base64c && \
  ./bootstrap && ./configure --prefix=/usr && make install && \
  cd .. && \
  rm -rf base64c


CMD [ "bash" ]

# vim: ft=dockerfile
