# Container for compilation test against musl system
# We choose AlpineLinux because OpenWRT compiler is not as easy to setup

FROM troyfontaine/alpinelinux:latest

ENV HOME /root

RUN \
  apk update upgrade && \
  apk add \
      ca-certificates curl git coreutils \
      make cmake pkgconf gcc perl \
      musl-dev argp-standalone \
      curl-dev libevent-dev uriparser-dev \
      uthash-dev \
      lua5.1-dev \
      asciidoc bash

RUN \
  wget "https://sourceforge.net/projects/libb64/files/libb64-1.2.1.zip" && \
  unzip "libb64-1.2.1.zip" && rm "libb64-1.2.1.zip" && \
  cd "libb64-1.2.1" && \
  CFLAGS=-fPIC make -C src && \
  cp src/libb64.a /usr/lib/ && \
  cp -r include/b64 /usr/include/ && \
  cd .. && rm -rf "libb64-1.2.1"


CMD [ "bash" ]

# vim: ft=dockerfile
