# Container for compilation test against system used on build servers
FROM debian:stable

ENV HOME /root

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get -y install --no-install-recommends \
    ca-certificates curl git bzip2 \
    autoconf autoconf-archive automake libtool \
    make cmake pkg-config gcc \
    libcurl4-openssl-dev libevent-dev libssl-dev liburiparser-dev \
    libarchive-dev \
    libb64-dev uthash-dev \
    liblua5.1-0-dev \
    libfile-slurp-perl \
    && \
  apt-get clean

CMD [ "bash" ]

# vim: ft=dockerfile
