BINARIES += src/pkgupdate/pkgupdate

PKGUPDATE_EMBED := $(abspath $(wildcard $(S)/src/pkgupdate/internal/*))
$(O)/.gen/src/pkgupdate/uriinternal.embedlist: $(S)/src/lib/gen_embed.sh $(S)/src/lib/embed_types.h $(PKGUPDATE_EMBED)
	$(M) GEN $@
	$(Q)mkdir -p $(dir $@)
	$(Q)$< "" uriinternal $(S)/src/lib/embed_types.h $(PKGUPDATE_EMBED) >$@

pkgupdate_MODULES := \
	main \
	uriinternal.embed

pkgupdate_LOCAL_LIBS := updater

DOCS += src/pkgupdate/interaction
