BINARIES += src/pkgupdate/pkgupdate

$(O)/.gen/src/pkgupdate/uriinternal.embedlist: EMBEDS := $(wildcard $(S)/src/pkgupdate/internal/*)

pkgupdate_MODULES := \
	main \
	uriinternal.embed

pkgupdate_LOCAL_LIBS := updater
