#!/bin/sh

# Copyright (c) 2016, CZ.NIC, z.s.p.o. (http://www.nic.cz/)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the CZ.NIC nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CZ.NIC BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

UPDATER_CONFIG=auto.lua # TODO change this to real path
OPKG=/bin/opkg # Path to opkg

ARGS=""
EXC=0

OPERATION="n"
while [ "$1" ]; do
	case "$1" in
		install)
			OPERATION="i"
			break
			;;
		remove)
			OPERATION="r"
			break
			;;
		*)
			ARGS="$ARGS $1"
			;;
	esac
	shift
done
shift

if [[ "$OPERATION" == "n" ]]; then
	# Not install or remove operation
	$OPKG $ARGS $@
	exit $?
fi


while [ "$1" ]; do
	if [[ `echo "$1" | sed 's/^-/+/'` != "$1" ]]; then # ignore options
		ARGS="$ARGS $1"
		shift
		continue
	fi
	PACKAGES=`echo -e "$PACKAGES\n$1"`
	shift
done


install() {
	$OPKG $ARGS install "$1"
	if [[ "$?" -ne 0 ]]; then
		# opkg failed, probably some problem with package. Lets not change anything
		EXC=255
		return
	fi

	if [[ -f "$1" ]]; then
		echo "Warning: Locally installed packages will be removed with the next automatic update!" 1>&2
		return
	fi

	INSPKG=`grep -e "^Install \"$1\"" "$UPDATER_CONFIG"` # Check if installed
	if [[ -z "$INSPKG" ]]; then
		# Package was never installed
		echo "Install \"$1\"" >>"$UPDATER_CONFIG"
	fi
}

remove() {
	# Lets remove that package
	$OPKG $ARGS remove "$1"
	if [[ "$?" -ne 0 ]]; then
		# opkg failed. But continue anyway
		EXC=255
	fi

	INSPKG=`grep -e "^Install \"$1\"" "$UPDATER_CONFIG"` # Check if installed
	if [[ -n "$INSPKG" ]]; then
		# Package is installed
		sed -e "/^Install \"$1\"/d" "$UPDATER_CONFIG" -i
	fi
}


# Check if $UPDATER_CONFIG exists. Otherwise create.
if [[ ! -f "$UPDATER_CONFIG" ]]; then
	echo "-- A file with auto-generated Install commands. Do not edit." > "$UPDATER_CONFIG"
fi

for P in $PACKAGES; do
	case "$OPERATION" in
		i) # Install
			install "$P"
			;;
		r) # Remove
			remove "$P"
			;;
	esac
done
exit $EXC
