# Container for compilation test against musl system
# We choose AlpineLinux because OpenWRT compiler is not as easy to setup

FROM troyfontaine/alpinelinux:latest

ENV HOME /root

RUN \
  apk update upgrade && \
  apk add \
      ca-certificates curl git \
      make cmake pkgconf gcc perl \
	  musl-dev argp-standalone \
      curl-dev libevent-dev uriparser-dev \
      uthash-dev \
      lua5.1-dev \
      asciidoc bash
# Note: missing libb64

CMD [ "bash" ]

# vim: ft=dockerfile
