
TRANS_SYS_TESTS := \
	help \
	install \
	remove \
	remove-nonexistent \
	reboot-recover

UPD_SYS_TESTS := \
	plan \
	plan-unapproved \
	steal-confs \
	simple-update \
	multiple-repos \
	pkg-content \
	reboot \
	provides \
	abi-change \
	replan \
	list-dir \
	force-downgrade

MIGRATE_SYS_TESTS := \
	auto-migrate-pkgs

.PHONY: test-sys valgrind-sys check

check: test-sys valgrind-sys

# As secondary tool we use pkgupdate in reboot-recover test
test-sys-opkg-trans-reboot-recover: $(O)/bin/pkgupdate
valgrind-sys-opkg-trans-reboot-recover: $(O)/bin/pkgupdate

define BUILD_PACKAGE

$(O)/repos/$(1)/$(2)/$(3).ipk: $(shell find $(S)/tests/system/$(1)/$(2))
	@mkdir -p "$$(@D)"
	$(S)/utils/opkg-create/opkg-create-package $(S)/tests/system/$(1)/$(2)/$(3) $$(@D)

endef

define BUILD_REPO

$(eval $(foreach PACKAGE,$(patsubst $(S)/tests/system/$(1)/$(2)/%,%,$(wildcard $(S)/tests/system/$(1)/$(2)/*)),$(call BUILD_PACKAGE,$(1),$(2),$(PACKAGE))))

$(O)/repos/$(1)/$(2)/Packages.gz: $(patsubst $(S)/tests/system/%,$(O)/repos/%.ipk,$(wildcard $(S)/tests/system/$(1)/$(2)/*))
	@mkdir -p "$$(@D)"
	$(S)/utils/opkg-create/opkg-create-repo $$(@D)

endef

define DO_SYS_TEST

test-sys: test-sys-$(1)-$(2)
valgrind-sys: valgrind-sys-$(1)-$(2)
.PHONY: test-sys-$(1)-$(2) valgrind-sys-$(1)-$(2)

$(eval $(foreach REPO,$(patsubst $(S)/tests/system/$(2)/%,%,$(wildcard $(S)/tests/system/$(2)/repo*)),$(call BUILD_REPO,$(2),$(REPO))))

test-sys-$(1)-$(2): $(O)/bin/$(1) $(patsubst $(S)/tests/system/%,$(O)/repos/%/Packages.gz,$(wildcard $(S)/tests/system/$(2)/repo*))
	LAUNCHER= S=$(S) O=$(abspath $(O)) $(S)/tests/system/run $(1) $(S)/tests/system/$(2)

valgrind-sys-$(1)-$(2): $(O)/bin/$(1) $(patsubst $(S)/tests/system/%,$(O)/repos/%/Packages.gz,$(wildcard $(S)/tests/system/$(2)/repo*))	LAUNCHER="$(VALGRIND)" S=$(S) O=$(abspath $(O)) $(S)/tests/system/run $(1) $(S)/tests/system/$(2)

endef

$(eval $(foreach TEST,$(TRANS_SYS_TESTS),$(call DO_SYS_TEST,opkg-trans,$(TEST))))
$(eval $(foreach TEST,$(UPD_SYS_TESTS),$(call DO_SYS_TEST,pkgupdate,$(TEST))))
$(eval $(foreach TEST,$(MIGRATE_SYS_TESTS),$(call DO_SYS_TEST,pkgmigrate,$(TEST))))
