
SYS_TESTS := \
	help \
	install

.PHONY: test-sys valgrind-sys check

check: test-sys valgrind-sys

define DO_SYS_TEST

test-sys: test-sys-$(1)-$(2)
valgrind-sys: valgrind-sys-$(1)-$(2)
.PHONY: test-sys-$(1)-$(2) valgrind-sys-$(1)-$(2)

test-sys-$(1)-$(2): $(O)/bin/$(1)
	LAUNCHER= SUPPRESS_LOG=1 S=$(S) O=$(O) $(S)/tests/system/run $(1) $(S)/tests/system/$(2)

valgrind-sys-$(1)-$(2): $(O)/bin/$(1)
	LAUNCHER="$(VALGRIND)" SUPPRESS_LOG=1 S=$(S) O=$(O) $(S)/tests/system/run $(1) $(S)/tests/system/$(2)

endef

$(eval $(foreach TEST,$(SYS_TESTS),$(call DO_SYS_TEST,opkg-trans,$(TEST))))
