#!/bin/bash

set -e

# Copyright 2016, CZ.NIC z.s.p.o. (http://www.nic.cz/)
#
# This file is part of the turris updater.
#
# Updater is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
# Updater is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Updater.  If not, see <http://www.gnu.org/licenses/>.

# This launches a system test. To run it:
# - Name of the tested binary as the 1st argument
# - Pass the path to the defining directory as the 2nd argument
# - Either set environment variables S and O, as in the makefiles,
#   or run it from the top level build directory with build-inside-sources.
# - Optionally, set LAUNCHER variable (for valgrind or something)

set -e

: ${O:=$(pwd)}
: ${S:=$(pwd)}
export TMPDIR="$O/testdir"
mkdir -p "$TMPDIR"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' SIGHUP SIGINT SIGQUIT SIGABRT SIGALRM SIGTERM SIGILL SIGPIPE EXIT
export ROOT_DIR="$TMP_DIR"/root
DEFINITION="$2"
DATA_DIR="$S"/tests/data

# Prepare the root directory for the run
cp -ar "$DEFINITION"/input "$TMP_DIR"/root
# Drop the .keep files, they are a hack for git to preserve directories
cp -ar "$DEFINITION"/output "$TMP_DIR"/output
if [ -f "$DEFINITION"/setup ] ; then
	. "$DEFINITION"/setup
fi
find "$TMP_DIR" -type f -name .keep -exec rm {} \;
# Launch it
export COVERAGEDIR="$O/.lua_coverage"
eval $LAUNCHER "$O"/bin/"$1" --model Turris --board unknown $(cat "$DEFINITION"/params)
# Do we need to de-randomize the output somehow?
if [ -f "$DEFINITION"/cleanup ] ; then
	. "$DEFINITION"/cleanup
fi
# Check it did what it should have
diff -u -N -r "$TMP_DIR"/output "$ROOT_DIR"
